#!/usr/bin/env node
// Reads every CSV file in data/ and writes src/data.js with the contents embedded
// as string constants.  Run this script whenever a CSV file is added or changed.
//   node scripts/build-data.js
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const dataDir = join(root, 'data');
const outPath = join(root, 'src', 'data.js');

const files = readdirSync(dataDir).filter(f => f.endsWith('.csv')).sort();

const entries = files.map(f => {
  const name  = basename(f, '.csv');
  const csv   = readFileSync(join(dataDir, f), 'utf-8');
  const rows  = csv.split('\n').slice(1).filter(l => l.trim()).length;
  const label = name.charAt(0).toUpperCase() + name.slice(1) + ` (${rows} rows)`;
  // Escape characters that would break a template literal.
  const escaped = csv.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  return { name, label, escaped };
});

const out = [
  '// AUTO-GENERATED by scripts/build-data.js — do not edit by hand.',
  '// Source files: data/*.csv',
  'export const BUILTIN_DATASETS = [',
  ...entries.map(({ name, label, escaped }) =>
    `  { value: ${JSON.stringify(name)}, label: ${JSON.stringify(label)}, csv: \`${escaped}\` },`
  ),
  '];',
  '',
].join('\n');

writeFileSync(outPath, out);
console.log(`Wrote src/data.js (${entries.length} dataset(s): ${entries.map(e => e.name).join(', ')})`);
