#!/usr/bin/env node
// Reads style.css and writes src/styles.js with the CSS injected at runtime.
// Run this script whenever style.css changes.
//   node scripts/build-css.js
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const cssPath = join(root, 'style.css');
const outPath = join(root, 'src', 'styles.js');

const css = readFileSync(cssPath, 'utf-8');
const escaped = css.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const out = [
  '// AUTO-GENERATED by scripts/build-css.js — do not edit by hand.',
  '// Source file: style.css',
  'const _style = document.createElement(\'style\');',
  `_style.textContent = \`${escaped}\`;`,
  'document.head.appendChild(_style);',
  '',
].join('\n');

writeFileSync(outPath, out);
console.log('Wrote src/styles.js');
