// AUTO-GENERATED by scripts/build-css.js — do not edit by hand.
// Source file: style.css
const _style = document.createElement('style');
_style.textContent = `* { box-sizing: border-box; margin: 0; padding: 0; }

#datadrag {
  display: flex;
  height: 100vh;
  font-family: sans-serif;
  overflow: hidden;
}

#palette {
  width: 160px;
  background: #f0f0f0;
  border-right: 1px solid #ccc;
  padding: 12px;
  display: flex;
  flex-direction: column;
  gap: 8px;
  flex-shrink: 0;
}

#palette h2 {
  font-size: 14px;
  color: #555;
  margin-bottom: 4px;
}

.palette-item {
  border: 1px solid #2980b9;
  border-radius: 3px;
  cursor: grab;
  user-select: none;
  padding: 5px 6px;
  font-size: 12px;
  color: #333;
  background: #e8f4fd;
  text-align: center;
}

.palette-item:hover { background: #cce4f5; }

#canvas-area {
  flex: 1;
  position: relative;
  background: #fafafa;
}

#canvas {
  width: 100%;
  height: 100%;
  cursor: default;
}

#run-all-btn {
  position: absolute;
  top: 8px;
  left: 8px;
  z-index: 50;
  font-size: 13px;
  padding: 4px 16px;
  cursor: pointer;
  background: #2980b9;
  color: white;
  border: none;
  border-radius: 4px;
}

#run-all-btn:hover { background: #2471a3; }

#ctx-menu {
  position: fixed;
  background: white;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-shadow: 2px 2px 8px rgba(0,0,0,0.15);
  z-index: 100;
  min-width: 130px;
}

#ctx-menu.hidden { display: none; }

.menu-item {
  padding: 8px 16px;
  cursor: pointer;
  font-size: 13px;
}

.menu-item:hover { background: #f0f0f0; }

.menu-item.label {
  color: #888;
  cursor: default;
  font-weight: bold;
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.menu-item.label:hover { background: white; }

.menu-separator {
  border-top: 1px solid #eee;
  margin: 2px 0;
}

/* --- Wide-block inline controls (rendered via foreignObject) --- */

.block-controls {
  display: flex;
  flex-direction: column;
  gap: 2px;
  height: 100%;
  font-size: 11px;
  justify-content: center;
}

.block-row {
  display: flex;
  align-items: center;
  gap: 4px;
  min-width: 0;
}

.block-file-input {
  flex: 1;
  font-size: 10px;
  min-width: 0;
  max-width: 160px;
  height: 18px;
}

.block-builtin-select {
  width: 100%;
  height: 18px;
  font-size: 11px;
  border: 1px solid #aac;
  border-radius: 3px;
}

.block-expr-input {
  font-size: 11px;
  width: 100%;
  height: 18px;
  padding: 1px 4px;
  border: 1px solid #aac;
  border-radius: 3px;
}

.csv-filename {
  flex: 1;
  font-size: 10px;
  color: #555;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.block-run-btn {
  font-size: 10px;
  padding: 2px 8px;
  cursor: pointer;
  background: #2980b9;
  color: white;
  border: none;
  border-radius: 3px;
  white-space: nowrap;
  flex-shrink: 0;
}

.block-run-btn:hover { background: #2471a3; }

/* --- Show modal --- */

#show-modal {
  position: fixed;
  inset: 0;
  z-index: 200;
  display: flex;
  align-items: center;
  justify-content: center;
}

#show-modal.hidden { display: none; }

#show-overlay {
  position: absolute;
  inset: 0;
  background: rgba(0,0,0,0.35);
}

#show-content {
  position: relative;
  background: white;
  border-radius: 6px;
  box-shadow: 0 4px 24px rgba(0,0,0,0.25);
  max-width: 90vw;
  max-height: 80vh;
  display: flex;
  flex-direction: column;
  min-width: 320px;
}

#show-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 16px 8px;
  border-bottom: 1px solid #eee;
  flex-shrink: 0;
}

#show-header h3 {
  font-size: 15px;
  font-weight: 600;
  color: #333;
  margin: 0;
}

#show-close {
  background: none;
  border: none;
  font-size: 16px;
  cursor: pointer;
  color: #888;
  padding: 0 4px;
  line-height: 1;
}

#show-close:hover { color: #333; }

#show-body {
  overflow: auto;
  padding: 12px 16px;
}

.df-table {
  border-collapse: collapse;
  font-size: 12px;
  white-space: nowrap;
}

.df-table th {
  background: #f0f4f8;
  border: 1px solid #d0d8e0;
  padding: 4px 10px;
  text-align: left;
  font-weight: 600;
  color: #444;
}

.df-table td {
  border: 1px solid #e0e8f0;
  padding: 3px 10px;
  color: #333;
}

.df-table tr:nth-child(even) td { background: #f8fafc; }

.df-truncated {
  font-size: 11px;
  color: #888;
  margin-top: 8px;
  text-align: right;
}
`;
document.head.appendChild(_style);
